development:
  adapter: postgresql
  encoding: unicode
  database: class_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: class_test
  pool: 5
  username: postgres
  password: postgres
